// Dummy data for the table - replace with actual data fetching
export const customerData = [
    {
        no: 1,
        customer: "00123",
        clientName: "Jhon Doe",
        ld: "LD256000001",
        risk: "Very High Risk",
        check: "Post-disbursement",
        approver: "Admin",
        type1: "Active",
        type2: "N/A",
        type3: "N/A",
        type4: "N/A",
        type5: "N/A",
    },
    {
        no: 2,
        customer: "00456",
        clientName: "Jane Smith",
        ld: "LD256000002",
        risk: "Medium Risk",
        check: "Facility Review",
        approver: "Manager",
        type1: "Pending",
        type2: "N/A",
        type3: "N/A",
        type4: "N/A",
        type5: "N/A",
    },
    {
        no: 3,
        customer: "00789",
        clientName: "Peter Jones",
        ld: "LD256000003",
        risk: "Low Risk",
        check: "Default-90 Days",
        approver: "Analyst",
        type1: "Completed",
        type2: "N/A",
        type3: "N/A",
        type4: "N/A",
        type5: "N/A",
    },
]