export const userData = [
    {
        id: 1,
        userId: "USR001",
        userName: "John Doe",
        profileName: "Admin",
        isLocked: "F",
        remark: "Super Administrator",
        isADUser: "Y",
        bookedDate: "2024-01-15",
        inputter: "System",
        curNo: "001",
    },
    {
        id: 2,
        userId: "USR002",
        userName: "Jane Smith",
        profileName: "Manager",
        isLocked: "F",
        remark: "Credit Manager",
        isADUser: "Y",
        bookedDate: "2024-01-16",
        inputter: "Admin",
        curNo: "002",
    },
    {
        id: 3,
        userId: "USR003",
        userName: "Bob Johnson",
        profileName: "User",
        isLocked: "T",
        remark: "Inactive User",
        isADUser: "N",
        bookedDate: "2024-01-17",
        inputter: "Admin",
        curNo: "003",
    },
    {
        id: 4,
        userId: "USR004",
        userName: "John Doe",
        profileName: "Admin",
        isLocked: "F",
        remark: "Super Administrator",
        isADUser: "Y",
        bookedDate: "2024-01-15",
        inputter: "System",
        curNo: "004",
    },
    {
        id: 5,
        userId: "USR005",
        userName: "Jane Smith",
        profileName: "Manager",
        isLocked: "F",
        remark: "Credit Manager",
        isADUser: "Y",
        bookedDate: "2024-01-16",
        inputter: "Admin",
        curNo: "005",
    },
    {
        id: 6,
        userId: "USR006",
        userName: "Bob Johnson",
        profileName: "User",
        isLocked: "T",
        remark: "Inactive User",
        isADUser: "N",
        bookedDate: "2024-01-17",
        inputter: "Admin",
        curNo: "006",
    },
    {
        id: 7,
        userId: "USR007",
        userName: "John Doe",
        profileName: "Admin",
        isLocked: "F",
        remark: "Super Administrator",
        isADUser: "Y",
        bookedDate: "2024-01-15",
        inputter: "System",
        curNo: "007",
    },
    {
        id: 8,
        userId: "USR008",
        userName: "Jane Smith",
        profileName: "Manager",
        isLocked: "F",
        remark: "Credit Manager",
        isADUser: "Y",
        bookedDate: "2024-01-16",
        inputter: "Admin",
        curNo: "008",
    },
    {
        id: 9,
        userId: "USR009",
        userName: "Bob Johnson",
        profileName: "User",
        isLocked: "T",
        remark: "Inactive User",
        isADUser: "N",
        bookedDate: "2024-01-17",
        inputter: "Admin",
        curNo: "009",
    },
]
